version: 2

updates:
  - package-ecosystem: npm
    directory: /zalo-mini-app
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      frontend-minor-patches:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /firebase/functions
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      backend-minor-patches:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
